config/routes.rb
Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  devise_for :users

  devise_scope :user do
    root to: 'devise/registrations#new'
  end

  resources :users, only: :none do
    member do
      resources :payment_methods, except: [:index, :show],
        path: 'wallet', param: :payment_method_id
      resources :categories, except: [:index, :show], param: :category_id

      get '/profile', to: 'profiles#show'
    end
  end

  namespace :dashboards do
    get :current
    get :trends
  end

  resources :transactions
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @payment_methods = current_user.payment_methods.
      reject(&:default_payment_method?)
    @categories = current_user.categories.
      reject(&:default_category?)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def fake_masked_password
    "#{'*' * 8}".html_safe
  end
end

app/views/profiles/_categories.html.haml
%h3 Categories

- @categories.each do |category|
  .col-md-12
    %span.col-md-11.label-font
      = link_to category.title.titleize, edit_category_path(current_user.id, category.id)
    %span.col-md-1
      = link_to fa_icon("trash-o", class: "fa-2x"), category_path(current_user, category.id), method: :delete, data: {confirm: "Are you sure?"}

app/views/profiles/_payment_methods.html.haml
%h3 Payment Methods

- @payment_methods.each do |payment_method|
  .col-md-12
    %span.col-md-11.label-font
      = link_to payment_method.name.titleize, edit_payment_method_path(current_user.id, payment_method.id)
    %span.col-md-1
      = link_to fa_icon("trash-o", class: "fa-2x"), payment_method_path(current_user, payment_method.id), method: :delete, data: {confirm: "Are you sure?"}

app/views/profiles/_personal_information.html.haml
%h3 Personal

%span.col-md-2
  %p.label-font Email
%span.col-md-10
  %p.label-font= current_user.email

%span.col-md-2
  %p.label-font Password
%span.col-md-10
  %p.label-font= fake_masked_password

%span.col-md-10.col-md-offset-2
  %p.label-font
    %b= link_to "Change password (coming soon)", profile_user_path

app/views/profiles/show.html.haml
%h1.text-center
  Profile

.col-md-6.col-md-offset-3
  = render 'personal_information'

.col-md-6.col-md-offset-3
  = render 'payment_methods'

.col-md-6.col-md-offset-3
  = render 'categories'