config/routes.rb
Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  devise_for :users

  devise_scope :user do
    root to: 'devise/registrations#new'
  end

  resources :users, only: :none do
    member do
      resources :payment_methods, except: [:index, :show],
        path: 'wallet', param: :payment_method_id
      resources :categories, except: [:index, :show], param: :category_id

      get '/profile', to: 'profiles#show'
    end
  end

  namespace :dashboards do
    get :current
    get :trends
  end

  resources :transactions
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :require_user
  before_action :set_transactions, except: [:new]

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = transactions.build(transaction_params)

    if @transaction.save
      redirect_to transactions_path
    else
      render :new
    end
  end

  def index
    _transactions = transactions.by_month(params[:month],
                                               params[:year]).
      includes(:payment_method, :category)
    @monthly_total = _transactions.total
    @transactions = Kaminari.paginate_array(_transactions).page(params[:page])
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def update
    @transaction = Transaction.find(params[:id])
    if @transaction.update(transaction_params)
      redirect_to transaction_path
    else
      render :edit
    end
  end

  def destroy
    @transaction = Transaction.find(params[:id]).destroy
    redirect_to transaction_path
  end

  private
  def set_transactions
    @transactions = current_user.transactions
  end

  def transactions
    @transactions
  end

  def transaction_params
    params.require(:transaction).permit(:date,
                             :amount,
                             :description,
                             :payment_method_id,
                             :category_id,
                             :user_id)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def active_month_link(month)
    active_link_to month.upcase,
      transactions_path(month: month, year: Date.current.year),
      active: active_month,
      class: 'month-link'
  end

  def active_month
    if request.query_parameters.has_key?("month") &&
        valid_month?(request.query_parameters["month"])
      # /#{month}/i
      /#{request.query_parameters["month"]}/i
    else
      /#{Date.current.strftime("%B")}/i
    end
  end

  def valid_month?(month)
    Date::MONTHNAMES.compact.map(&:downcase).include?(month.to_s.downcase)
  end
end

app/views/transactions/_form.html.haml
.col-md-2.col-md-offset-5
  = simple_form_for @transaction do |f|
    = f.input :date, as: :date
    = f.input :description
    = f.input :amount
    - if current_user.categories.blank?
      = f.label "Category"
      = link_to "Add New Category", new_category_path(current_user)
    - else
      = f.association :category,
          collection: current_user.categories,
          selected: (@transaction.category_id || current_user.default_category),
          value_method: :id
    - if current_user.payment_methods.blank?
      = f.label "Payment method"
      = link_to "Add New Payment Method", new_payment_method_path(current_user)
    - else
      = f.association :payment_method,
          collection: current_user.payment_methods,
          selected: (@transaction.payment_method_id || current_user.default_payment_method),
          value_method: :id

    .form-actions
      = f.button :submit

app/views/transactions/_transactions.html.haml
%table.table.table-striped
  %thead
    %th.col-md-1 Date
    %th.col-md-3 Description
    %th.col-md-2 Amount
    %th.col-md-2 Category
    %th.col-md-3 Payment Method
    %th.col-md-1 Actions

  %tbody
    - @transactions.each do |transaction|
      %tr
        %td= formatted_date(transaction.date)
        %td= transaction.description
        %td= number_to_currency(transaction.amount)
        %td= transaction.category.title
        %td= transaction.payment_method.name
        %td
          %span.col-md-6= link_to fa_icon("pencil-square-o", class: "fa-2x"), edit_transaction_path(transaction)
          %span.col-md-6= link_to fa_icon("trash-o", class: "fa-2x"), transaction, method: :delete, data: {confirm: "Are you sure?"}

app/views/transactions/edit.html.haml
= render 'form'

app/views/transactions/index.html.haml
.col-md-10.col-md-offset-1
  .col-md-12.month-list-container
    - month_names.each do |month|
      %span.col-md-1.month-list
        %p= active_month_link(month)
  .text-center.grand-total
    %p= number_to_currency(@monthly_total)

  = render 'transactions'
  .text-center= paginate @transactions

app/views/transactions/new.html.haml
.text-center
  %h1 New Transaction
= render 'form'